//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blockchaninaccounts.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BlockChainEntities : DbContext
    {
        public BlockChainEntities()
            : base("name=BlockChainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Coin_Master> tbl_Coin_Master { get; set; }
        public virtual DbSet<USER_SESSION> USER_SESSION { get; set; }
    
        public virtual ObjectResult<GetActivityLogList_Result> GetActivityLogList(string userid)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetActivityLogList_Result>("GetActivityLogList", useridParameter);
        }
    
        public virtual ObjectResult<GetCoinsList_Result> GetCoinsList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCoinsList_Result>("GetCoinsList");
        }
    
        public virtual ObjectResult<GetRecentTransactionList_Result> GetRecentTransactionList(string userid)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRecentTransactionList_Result>("GetRecentTransactionList", useridParameter);
        }
    
        public virtual ObjectResult<GetTotalBalance_Result> GetTotalBalance(string userid, Nullable<int> coinid)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            var coinidParameter = coinid.HasValue ?
                new ObjectParameter("coinid", coinid) :
                new ObjectParameter("coinid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTotalBalance_Result>("GetTotalBalance", useridParameter, coinidParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> GetTotalTransaction(string userid)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("GetTotalTransaction", useridParameter);
        }
    
        public virtual ObjectResult<GetWalletBalance_Result> GetWalletBalance(string userid)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWalletBalance_Result>("GetWalletBalance", useridParameter);
        }
    }
}
