//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blockchaninaccounts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Coin_Master
    {
        public int Id { get; set; }
        public string CoinName { get; set; }
        public string CoinAbbreviation { get; set; }
        public Nullable<decimal> MinimumSendtAmount { get; set; }
        public Nullable<decimal> MaximumSendAmount { get; set; }
        public Nullable<decimal> MinimumReceivetAmount { get; set; }
        public Nullable<decimal> MaximumReceiveAmount { get; set; }
        public Nullable<decimal> MinimumExchagetAmount { get; set; }
        public Nullable<decimal> MaximumExchangeAmount { get; set; }
        public Nullable<decimal> MinimumSellAmount { get; set; }
        public Nullable<decimal> MaximumSellAmount { get; set; }
        public Nullable<decimal> SellFee { get; set; }
        public Nullable<decimal> SellTax { get; set; }
        public Nullable<decimal> MinimumBuyAmount { get; set; }
        public Nullable<decimal> MaximumBuyAmount { get; set; }
        public Nullable<decimal> BuyFee { get; set; }
        public Nullable<decimal> BuyTax { get; set; }
        public Nullable<decimal> SendTransactionFeeReguler { get; set; }
        public Nullable<decimal> SendTransactionFeeNormal { get; set; }
        public Nullable<decimal> SendTransactionFeeHigh { get; set; }
        public Nullable<bool> IsSend { get; set; }
        public Nullable<bool> IsReceive { get; set; }
        public Nullable<bool> IsSell { get; set; }
        public Nullable<bool> IsBuy { get; set; }
        public Nullable<bool> IsExchange { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.Guid> CreatedUserId { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.Guid> UpdatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public Nullable<decimal> MarkupBuy { get; set; }
        public Nullable<decimal> MarkupSell { get; set; }
        public Nullable<decimal> MarkupExchange { get; set; }
    }
}
