//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blockchaninaccounts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_SESSION
    {
        public string SessionToken { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
